#!/usr/bin/env bash

set -eo pipefail

# config
folder=${DMENU_DICTAPHONE_FOLDER:-~/Dictaphone}
sub=${DMENU_DICTAPHONE_SUB:-"$(date +%Y)"}
audio_settings=${DMENU_RECORD_AUDIO_SETTINGS:-"-c:a aac -b:a 320k"}
dmenu=${DMENU_RECORD_DMENU:-"dmenu -i -p"}

# useful variables
datetime="$(date +%Y-%m-%d_%H-%M-%S.%3N)"
foldersub="$folder/$sub"

# creates the year subfolder if not exist
[ -d "$foldersub" ] || mkdir -p "$foldersub"


ask_to_end() {
    local response=$(printf "no\\nyes" | $dmenu "end recording:") && \
    [ "$response" = "yes" ] && kill_recording
}

send_notification_begin() {
    notify-send "Started Recording!" "The file will be saved at ${foldersub}!"
}

send_notification_end() {
    notify-send "Finished Recording!" "The file was saved to your disk at ${foldersub}!"
}

dmenu_ask() {
    local response=$(printf "yes\\nno" | $dmenu "start recording:")
    if ! [ "$response" = "yes" ]; then
        exit 0
    fi
}

print_args() {
    local filename="$foldersub/${datetime}_audio.m4a"
    local args="-y -f pulse -thread_queue_size 1024 -i $(get_pulse_source) -ac 1 $audio_settings $filename"

    echo "$args" | sed 's/  */ /g'
}

ffmpeg_record() {
    ffmpeg $(print_args) &

    echo $! > "/tmp/dmenu-dictaphone.pid"
}

get_pulse_source() {
    echo ""$(pactl get-default-source)".monitor"
}

kill_recording() {
    kill -15 "$(cat "/tmp/dmenu-dictaphone.pid")"
    rm -f "/tmp/dmenu-dictaphone.pid"
}

ask_recording() {
    dmenu_ask
    ffmpeg_record
}

main() {
    if [ "$1" == "--print" ]; then
        dmenu_ask
        echo "ffmpeg $(print_args)"
        exit 0
    fi

    if [ -f "/tmp/dmenu-dictaphone.pid" ] && ! ps -p "$(cat "/tmp/dmenu-dictaphone.pid")" > /dev/null; then
        notify-send "dmenu-dictaphone: Error" "Cannot find PID; Cleaned. Try running the script again!"
        rm /tmp/dmenu-dictaphone.pid
        ask_recording && send_notification_begin
        exit 0
    fi

    if [ -f "/tmp/dmenu-dictaphone.pid" ]; then
        ask_to_end && \
        send_notification_end && \
        exit 0
    else
        ask_recording && send_notification_begin
    fi
}

main "$@"
